apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flags-deployment
  labels:
    app: feature-flags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-flags
  template:
    metadata:
      # kubectl rollout history deployment/feature-flags-deployment
      #annotations:
      #  kubernetes.io/change-cause: "Updated image to $(Build.BuildId)"
      labels:
        app: feature-flags
    spec:
      containers:
        - name: feature-flags
          image: agilesolutions/feature-flags:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 15
          lifecycle:
            preStop:
              httpGet:
                path: /unhealthy
                port: http
#          terminationGracePeriodSeconds: 10
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: false
          env:
            - name: LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
      imagePullSecrets:
        - name: my-acr-secret
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flags-loadbalancer-service
  labels:
    app: feature-flags
spec:
  type: LoadBalancer
  selector:
    app: feature-flags
  ports:
    - port: 80
      targetPort: 80