# template.yml
parameters:
  - name: SASToken
    type: string
    default: "NA"
  - name: environment
    type: string
    default: 'dev'

stages:
  - stage: Deploy_${{ parameters.environment }}
    variables:
      ${{ if eq(parameters.environment, 'dev' ) }}:
        vmSku: B2s
      ${{ if eq(parameters.environment, 'qa' ) }}:
        vmSku: B2ms
      ${{ if eq(parameters.environment, 'prod' ) }}:
        vmSku: B4ms

    jobs:
      - job: Deploy_${{ parameters.environment }}_Job
        steps:
          - checkout: none
          - script: |
              echo "SAS token: ${{ parameters.SASToken }}"
              echo "Expected SKU = $(vmSku)"
              echo "Deploying to ${{ parameters.environment }}"
            displayName: "Print SAS token"
