trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  serviceName: 'poc-feature-flags'
  path: './$(serviceName)'
  dockerRegistryServiceConnection: 'dockerhub' # name of ACR service connection
  imageRepository: 'agilesolutions/feature-flags' # name of image repository
  containerRegistry: 'Docker Hub' # name of Azure container registry
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Cache@2
      displayName: configure gradle caching
      continueOnError: true
      inputs:
        key: 'gradle | "$(Agent.OS)" $(path)/build.gradle'
        restoreKeys: |
          gradle | "$(Agent.OS)"
          gradle
        path: '$(Pipeline.Workspace)/.gradle'

    - task: Gradle@2
      displayName: 'build service'
      inputs:
        gradleWrapperFile: '$(path)/gradlew'
        workingDirectory: '$(path)'
        options: '--no-daemon'
        tasks: '--info build -x test'

    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: |
          $(tag)

    - publish: manifests
      artifact: manifests