# variable-scopes
trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment Name
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - prod

stages:
  - stage: Stage1
    jobs:
      - job: Stage1_Job1
        steps:
          - script: |
              echo "##vso[task.setvariable variable=SASToken;isOutput=true]SASTokenValue"
            displayName: Stage1_Job1_Script1
            name: Stage1_Job1_Script1
          - script: |
              echo "The value of SASToken: $(Stage1_Job1_Script1.SASToken)"
            displayName: Stage1_Job1_Script2
            name: Stage1_Job1_Script2
      - job: Stage1_Job2
        dependsOn: Stage1_Job1
        variables:
          - name: NewSASToken
            value: $[dependencies.Stage1_Job1.outputs['Stage1_Job1_Script1.SASToken']]
        steps:
          - checkout: none
          - script: |
              echo "The value of SASToken is $(NewSASToken)"
            displayName: Stage1_Job2_Script1
            name: Stage1_Job2_Script1
  - stage: Stage2
    variables:
      - name: NewSASToken
        value: $[stageDependencies.Stage1.Stage1_Job1.outputs['Stage1_Job1_Script1.SASToken']]
    jobs:
      - job: Stage2_Job1
        steps:
          - checkout: none
          - script: |
              echo "The value of SASToken in Stage2: $(NewSASToken)"
            displayName: Stage2_Job1_Script1
            name: Stage2_Job1_Script1
          - template: templates/template.yml
            parameters:
              token: $(NewSASToken)
              environment: ${{ parameters.environment }}
